### ISSUE TITLE
Weirdness in the server terminal

### ISSUE THREAD

**Issue by Kynick** [Secrets-of-Sosaria/World#3]
After leaving the server on for a while after i had closed the client, I came back to it and saw a few of these between autosaves:

```
WARNING: Automatic backup FAILED: System.IO.DirectoryNotFoundException: Could not find a part of the path.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Server.Misc.Cleanup.RemoveScript(String script)
   at Server.Misc.Cleanup.RemoveScripts()
   at Server.Misc.AutoSave.Backup()
   at Server.Misc.AutoSave.Save(Boolean permitBackgroundWrite)
Core: Using dual save strategy
Game: Saving...Closing Save Files...
Save done in 0.26 seconds.
```

Doesn't stop me from logging in again, so not sure what its all about

**Comment by Kynick** [comment]
I let it run again after a restart, and its still the same.  Checked the backup folder, and its still making them

**Comment by AxelDominatoR** [comment]
If you're on Windows and your World directory is nested inside a few others, there's a good chance you're hitting the 260 characters limit for file paths.

**Comment by Kynick** [comment]
for an unexplained reason, the issue has gone away for me
